### ISSUE TITLE
renderGraph always produces a "digraph"

### ISSUE THREAD

**Issue by rpglover64** [NorfairKing/haphviz#2]
Looking at [this](https://github.com/NorfairKing/haphviz/blob/645cdafe484635a1abf0ee70173b51bb91f48561/src/Text/Dot/Render.hs#L36) code, regardless of whether the graph is directed or not, the dot output is always a "digraph".

**Comment by NorfairKing** [comment]
Wow, how did that ever end up there. Lemme fix that!
