### ISSUE TITLE
Graphviz

### ISSUE THREAD

**Issue by hanjoosten** [NorfairKing/haphviz#3]
No insult ment, but did you consider using the [graphviz](http://hackage.haskell.org/package/graphviz) package? Then you'd have a headstart, and you could focus on what you really want to do.

**Comment by NorfairKing** [comment]
I explained why I'm not using that package [here](https://www.reddit.com/r/haskell/comments/3xik2o/cs_syd_haphviz_graphviz_code_generation_with/)
