### ISSUE TITLE
Compile failure with GHC 7.8

### ISSUE THREAD

**Issue by hvr** [NorfairKing/haphviz#4]
see below

```
Configuring component lib from haphviz-0.2.0.1
Preprocessing library haphviz-0.2.0.1...
[1 of 9] Compiling Text.Dot.Types.Internal ( src/Text/Dot/Types/Internal.hs, /tmp/matrix-worker/1480708206/dist-newstyle/build/x86_64-linux/ghc-7.8.4/haphviz-0.2.0.1/build/Text/Dot/Types/Internal.o )

src/Text/Dot/Types/Internal.hs:78:10:
    Not in scope: type constructor or class ‘Monoid’
    Perhaps you meant ‘Monad’ (imported from Prelude)

```

**Comment by NorfairKing** [comment]
Thanks for showing me. Will up the cabal version bound for base.

**Comment by hvr** [comment]
@NorfairKing btw/jfyi (in case you are not aware), you can easily fixup the meta-data for the two affected releases via

 - https://hackage.haskell.org/package/haphviz-0.2.0.1/haphviz.cabal/edit
 - https://hackage.haskell.org/package/haphviz-0.2.0.0/haphviz.cabal/edit

**Comment by NorfairKing** [comment]
Aha, so no need to rerelease? That makes things easier...
